
# Basic
name: "ki2naiver"

author:
  #facebook: your-id
  #youtubeUser: your-id
  #youtubeChannel: your-id
  #twitter: your-id
  github: ki2naiver
  #stackoverflow: your-id
  #linkedin: your-id
  #pinterest: your-id
  #googlePlus: your-id
  #instagram: your-id
  reddit: farpras
  #medium: your-id
  #tumblr: your-id
  email: ki2naiver@protonmail.com

copyright:
  year: 2019
  name: ki2naiver

# Google-analytics
google-analytics:
  id: ""

# Disqus
disqus:
  id: "ki2naiver"

# URL
url: "http://blog.ki2naiver.id" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl: "/" # the subpath of your site, e.g. /blog

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Jakarta
permalink: /:day-:month-:year/:title/

# Pagination
paginate: 5
paginate_path: /page:num/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Navigation
nav:
  - name: "About"
    url: "/about"
  - name: "Archive"
    url: "/archive"
  - name: "Tags"
    url: "/tags"
  - name: "Github"
    url: "https://github.com/ki2naiver/blog"
  - name: "Mainpage"
    url: "http://ki2naiver.id"

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Scopes
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude: [vendor]
